# Generated by Django 3.1.3 on 2020-11-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allitem',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
    ]
