# Generated by Django 3.1.3 on 2020-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_allitem_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=10)),
                ('biz_num', models.IntegerField()),
                ('biz_url', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Allitem',
        ),
    ]
