# Generated by Django 3.1.3 on 2020-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20201107_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=10)),
                ('item_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openday', models.DateTimeField(auto_now_add=True)),
                ('opentime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
