# Generated by Django 3.1.3 on 2020-11-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_allitem_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_set',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.allitem'),
        ),
    ]
