# Generated by Django 3.1.3 on 2020-11-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_store_set_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allitem',
            old_name='store',
            new_name='store_name',
        ),
    ]
