# Generated by Django 3.1.3 on 2020-11-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20201107_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_set',
            name='openday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='store_set',
            name='opentime',
            field=models.TimeField(),
        ),
    ]
