# Generated by Django 3.1.3 on 2020-11-11 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allitem',
            old_name='store_name',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='biz_name',
        ),
        migrations.RenameField(
            model_name='store_set',
            old_name='store_name',
            new_name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='biz_address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='biz_insta',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='biz_tel',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store_set',
            name='notification',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store_set',
            name='pickuptime',
            field=models.TimeField(null=True),
        ),
    ]
