# Generated by Django 3.1.3 on 2020-11-11 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20201112_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='today_lineup',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.store'),
        ),
    ]
